const express = require("express");
const app = express();

const SendMoney = app.post("/send-money", (req, res) => {
  const data = req.body;

  const { sender, receiver, amount, description } = data;

  // todo: query sender balance here -> sender.id
  const sender_balance = 230.45;

  if (sender_balance < amount) {
    // sender does not have enough balance for the transaction
    res.status(500).json({
      ok: false,
      error: {
        message: "user does not have enough funds",
        typeError: "INSUFICIENT_FUNDS",
      },
    });
  } else {
    // todo:  query receiver balance -> receiver.id
    const receiver_current_balance = 100;
    const receiver_new_balance = receiver_current_balance + amount;

    //todo: save the receiver_new_balance for the receiver person

    // todo: save operation in the feed
    const transaction_data = {
      // id and timestamp (createdAt) is going to be generated by database
      sender: sender.id,
      receiver: receiver.id,
      amount,
      description,
    };

    res.json({
      ok: true,
    });
  }
});

module.exports = SendMoney;
